import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NeonAuthProvider } from "@/components/providers/NeonAuthProvider";
import { BottomNav } from "@/components/BottomNav";
import { getSession } from "@/lib/auth";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const isAuth = !!session?.user;
  const userRole = session?.user?.role as 'agent' | 'admin' | null || null;

  // Determine which agent's portfolio to link to
  // For now, default to 'demo'. This will be improved to extract from URL client-side
  const agentSlug = 'demo';

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NeonAuthProvider>
          {children}
          <div className="h-15 md:hidden" aria-hidden="true" />
          <BottomNav isAuth={isAuth} userRole={userRole} agentSlug={agentSlug} />
        </NeonAuthProvider>
      </body>
    </html>
  );
}
